---@class Athens
---@field config AthensConfig
---@field palette AthensPalette
local Athens = {}

---@class ItalicConfig
---@field strings boolean
---@field comments boolean
---@field operators boolean
---@field folds boolean
---@field emphasis boolean

---@class HighlightDefinition
---@field fg string?
---@field bg string?
---@field sp string?
---@field blend integer?
---@field bold boolean?
---@field standout boolean?
---@field underline boolean?
---@field undercurl boolean?
---@field underdouble boolean?
---@field underdotted boolean?
---@field strikethrough boolean?
---@field italic boolean?
---@field reverse boolean?
---@field nocombine boolean?

---@class AthensConfig
---@field terminal_colors boolean?
---@field undercurl boolean?
---@field underline boolean?
---@field bold boolean?
---@field italic ItalicConfig?
---@field strikethrough boolean?
---@field invert_selection boolean?
---@field invert_signs boolean?
---@field invert_tabline boolean?
---@field invert_intend_guides boolean?
---@field inverse boolean?
---@field overrides table<string, HighlightDefinition>?
---@field palette_overrides table<string, string>?
Athens.config = {
  terminal_colors = true,
  undercurl = true,
  underline = true,
  bold = true,
  italic = {
    strings = true,
    emphasis = true,
    comments = true,
    operators = false,
    folds = true,
  },
  strikethrough = true,
  invert_selection = false,
  invert_signs = false,
  invert_tabline = false,
  invert_intend_guides = false,
  inverse = true,
  palette_overrides = {},
  overrides = {},
  dim_inactive = false,
  transparent_mode = false,
}

-- main athens color palette
---@class AthensPalette
Athens.palette = {
      bg0 = "#090909", --[[manually darkened]]
      bg1 = "#1c1b19",
      bg2 = "#242320",
      bg3 = "#2c2b28",
      bg4 = "#353430",
      fg1 = "#958f88",
      fg2 = "#7b766f",
      fg3 = "#615d58",
      fg4 = "#494642",
      cursor = "#4f643c",
      modeline = "#272f30",
      active1 = "#303d3e",
      active2 = "#2c3637",
      inactive1 = "#232829",
      inactive2 = "#1e2122",
      clock12 = "#a28e59",
      clock01 = "#899659",
      clock02 = "#5a9f58",
      clock03 = "#5c9c84",
      clock04 = "#5e9a97",
      clock05 = "#6098a8",
      clock06 = "#6592ca",
      clock07 = "#9c82d3",
      clock08 = "#d067d2",
      clock09 = "#d86aa7",
      clock10 = "#dc6e79",
      clock11 = "#bf8259",
      bright_clock12 = "#ab8d00",
      bright_clock01 = "#849900",
      bright_clock02 = "#13a700",
      bright_clock03 = "#00a37c",
      bright_clock04 = "#00a09b",
      bright_clock05 = "#009db8",
      bright_clock06 = "#0095ef",
      bright_clock07 = "#a773ff",
      bright_clock08 = "#fb00fd",
      bright_clock09 = "#fe3ab6",
      bright_clock10 = "#fe4e68",
      bright_clock11 = "#d37900",
      dark_clock02 = "#0b7c00", --[[hsl=127, 100, 45]]
      dark_clock05 = "#007589", --[[hsl=217, 100, 45]]
      dark_clock10 = "#d5003b", --[[hsl= 71, 100, 45]]
      hi1 = "#b0b037",
      hi2 = "#3bbdac",
      err = "#c8575c",  --[[was error]]
      warning = "#817c55",
      success = "#00b953",
      var = "#958f88",
      func = "#b65a52",
      builtin = "#729599",
      keyword = "#729599",
      const = "#729599",
      comment = "#536e6f",
      str = "#6e9976",
      ltype = "#a28c6d", --[[ was type ]]
      preprocessor = "#5d9a91",
}

-- get a hex list of athens colors based on current bg and constrast config
local function get_colors()
  local p = Athens.palette
  local config = Athens.config

  for color, hex in pairs(config.palette_overrides) do
    p[color] = hex
  end

  local bg = vim.o.background

  local color_groups = {
    dark = {
      bg0 = p.bg0,
      bg1 = p.bg1,
      bg2 = p.bg2,
      bg3 = p.bg3,
      bg4 = p.bg4,
      fg0 = p.fg1,
      fg1 = p.fg1,
      fg2 = p.fg2,
      fg3 = p.fg3,
      fg4 = p.fg4,

      fake = "#ff00ff",

      cursor = p.cursor,
      modeline = p.modeline,
      active1 = p.active1,
      active2 = p.active2,
      inactive1 = p.inactive1,
      inactive2 = p.inactive2,
      hi1 = p.hi1,
      hi2 = p.hi2,
      err = p.err,
      warning = p.warning,
      success = p.success,
      var = p.var,
      func = p.func,
      builtin = p.builtin,
      keyword = p.keyword,
      const = p.const,
      comment = p.comment,
      str = p.str,
      ltype = p.ltype,
      preprocessor = p.preprocessor,

      red = p.bright_clock10,
      green = p.bright_clock02,
      yellow = p.bright_clock12,
      blue = p.bright_clock06,
      purple = p.bright_clock07,
      aqua = p.bright_clock05,
      orange = p.bright_clock11,
      neutral_red = p.clock10,
      neutral_green = p.clock02,
      neutral_yellow = p.clock12,
      neutral_blue = p.clock06,
      neutral_purple = p.clock07,
      neutral_aqua = p.clock05,
      neutral_orange = p.clock11,
      dark_red = p.dark_clock10,
      dark_green = p.dark_clock02,
      dark_aqua = p.dark_clock05,
      gray = p.fg1,
    },
    light = {
      bg0 = p.bg0,
      bg1 = p.bg1,
      bg2 = p.bg2,
      bg3 = p.bg3,
      bg4 = p.bg4,
      fg0 = p.fg1,
      fg1 = p.fg1,
      fg2 = p.fg2,
      fg3 = p.fg3,
      fg4 = p.fg4,

      fake = "#ff00ff",

      cursor = p.cursor,
      modeline = p.modeline,
      active1 = p.active1,
      active2 = p.active2,
      inactive1 = p.inactive1,
      inactive2 = p.inactive2,
      hi1 = p.hi1,
      hi2 = p.hi2,
      err = p.err,
      warning = p.warning,
      success = p.success,
      var = p.var,
      func = p.func,
      builtin = p.builtin,
      keyword = p.keyword,
      const = p.const,
      comment = p.comment,
      str = p.str,
      ltype = p.ltype,
      preprocessor = p.preprocessor,

      red = p.bright_clock10,
      green = p.bright_clock02,
      yellow = p.bright_clock12,
      blue = p.bright_clock06,
      purple = p.bright_clock07,
      aqua = p.bright_clock05,
      orange = p.bright_clock11,
      neutral_red = p.clock10,
      neutral_green = p.clock02,
      neutral_yellow = p.clock12,
      neutral_blue = p.clock06,
      neutral_purple = p.clock07,
      neutral_aqua = p.clock05,
      neutral_orange = p.clock11,
      dark_red = p.dark_clock10,
      dark_green = p.dark_clock02,
      dark_aqua = p.dark_clock05,
      gray = p.fg1,
    },
  }

  return color_groups[bg]
end

local function get_groups()
  local colors = get_colors()
  local config = Athens.config

  if config.terminal_colors then
    local term_colors = {
      colors.bg0,
      colors.neutral_red,
      colors.neutral_green,
      colors.neutral_yellow,
      colors.neutral_blue,
      colors.neutral_purple,
      colors.neutral_aqua,
      colors.fg4,
      colors.gray,
      colors.red,
      colors.green,
      colors.yellow,
      colors.blue,
      colors.purple,
      colors.aqua,
      colors.fg1,
    }
    for index, value in ipairs(term_colors) do
      vim.g["terminal_color_" .. index - 1] = value
    end
  end

  local groups = {
    AthensCursor = { fg = colors.cursor },
    AthensConstant = { fg = colors.const },
    AthensError = { fg = colors.err },
    AthensFunction = { fg = colors.func },
    AthensKeyword = { fg = colors.keyword },
    AthensPreProcessor = { fg = colors.preprocessor },
    AthensText = { fg = colors.fg1 },
    AthensType = { fg = colors.ltype },
    AthensVar = { fg = colors.var },
    AthensFg0 = { fg = colors.fg0 },
    AthensFg1 = { fg = colors.fg1 },
    AthensFg2 = { fg = colors.fg2 },
    AthensFg3 = { fg = colors.fg3 },
    AthensFg4 = { fg = colors.fg4 },
    AthensGray = { fg = colors.gray },
    AthensBg0 = { fg = colors.bg0 },
    AthensBg1 = { fg = colors.bg1 },
    AthensBg2 = { fg = colors.bg2 },
    AthensBg3 = { fg = colors.bg3 },
    AthensBg4 = { fg = colors.bg4 },
    AthensRed = { fg = colors.red },
    AthensRedBold = { fg = colors.red, bold = config.bold },
    AthensGreen = { fg = colors.green },
    AthensFg0Bold = { fg = colors.fg0, bold = config.bold },
    AthensGreenBold = { fg = colors.green, bold = config.bold },
    AthensYellow = { fg = colors.yellow },
    AthensYellowBold = { fg = colors.yellow, bold = config.bold },
    AthensBlue = { fg = colors.blue },
    AthensBlueBold = { fg = colors.blue, bold = config.bold },
    AthensPurple = { fg = colors.purple },
    AthensPurpleBold = { fg = colors.purple, bold = config.bold },
    AthensAqua = { fg = colors.aqua },
    AthensAquaBold = { fg = colors.aqua, bold = config.bold },
    AthensOrangeNeutral = { fg = colors.neutral_orange },
    AthensOrange = { fg = colors.orange },
    AthensOrangeBold = { fg = colors.orange, bold = config.bold },
    AthensRedSign = config.transparent_mode and { fg = colors.red, reverse = config.invert_signs }
      or { fg = colors.red, bg = colors.bg1, reverse = config.invert_signs },
    AthensGreenSign = config.transparent_mode and { fg = colors.green, reverse = config.invert_signs }
      or { fg = colors.green, bg = colors.bg1, reverse = config.invert_signs },
    AthensYellowSign = config.transparent_mode and { fg = colors.yellow, reverse = config.invert_signs }
      or { fg = colors.yellow, bg = colors.bg1, reverse = config.invert_signs },
    AthensBlueSign = config.transparent_mode and { fg = colors.blue, reverse = config.invert_signs }
      or { fg = colors.blue, bg = colors.bg1, reverse = config.invert_signs },
    AthensPurpleSign = config.transparent_mode and { fg = colors.purple, reverse = config.invert_signs }
      or { fg = colors.purple, bg = colors.bg1, reverse = config.invert_signs },
    AthensAquaSign = config.transparent_mode and { fg = colors.aqua, reverse = config.invert_signs }
      or { fg = colors.aqua, bg = colors.bg1, reverse = config.invert_signs },
    AthensOrangeSign = config.transparent_mode and { fg = colors.orange, reverse = config.invert_signs }
      or { fg = colors.orange, bg = colors.bg1, reverse = config.invert_signs },
    AthensOrangeNeutralSign = config.transparent_mode and { fg = colors.neutral_orange, reverse = config.invert_signs }
      or { fg = colors.neutral_orange, bg = colors.bg1, reverse = config.invert_signs },
    AthensRedUnderline = { undercurl = config.undercurl, sp = colors.red },
    AthensGreenUnderline = { undercurl = config.undercurl, sp = colors.green },
    AthensYellowUnderline = { undercurl = config.undercurl, sp = colors.yellow },
    AthensBlueUnderline = { undercurl = config.undercurl, sp = colors.blue },
    AthensPurpleUnderline = { undercurl = config.undercurl, sp = colors.purple },
    AthensAquaUnderline = { undercurl = config.undercurl, sp = colors.aqua },
    AthensOrangeUnderline = { undercurl = config.undercurl, sp = colors.orange },
    Normal = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg0 },
    NormalFloat = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg1 },
    NormalNC = config.dim_inactive and { fg = colors.fg0, bg = colors.bg1 } or { link = "Normal" },
    CursorLine = { bg = colors.bg1 },
    CursorColumn = { link = "CursorLine" },
    TabLineFill = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
    TabLineSel = { fg = colors.green, bg = colors.bg1, reverse = config.invert_tabline },
    TabLine = { link = "TabLineFill" },
    MatchParen = { bg = colors.bg3, bold = config.bold },
    ColorColumn = { bg = colors.bg1 },
    Conceal = { fg = colors.blue },
    CursorLineNr = { fg = colors.yellow, bg = colors.bg1 },
    NonText = { link = "AthensBg2" },
    SpecialKey = { link = "AthensFg4" },
    Visual = { bg = colors.bg3, reverse = config.invert_selection },
    VisualNOS = { link = "Visual" },
    Search = { fg = colors.yellow, bg = colors.bg0, reverse = config.inverse },
    IncSearch = { fg = colors.orange, bg = colors.bg0, reverse = config.inverse },
    CurSearch = { link = "IncSearch" },
    QuickFixLine = { link = "AthensPurple" },
    Underlined = { fg = colors.blue, underline = config.underline },
    StatusLine = { fg = colors.bg1, bg = colors.fg1, reverse = config.inverse },
    StatusLineNC = { fg = colors.bg1, bg = colors.fg4, reverse = config.inverse },
    WinBar = { fg = colors.fg4, bg = colors.bg0 },
    WinBarNC = { fg = colors.fg3, bg = colors.bg1 },
    WinSeparator = config.transparent_mode and { fg = colors.bg3, bg = nil } or { fg = colors.bg3, bg = colors.bg0 },
    WildMenu = { fg = colors.blue, bg = colors.bg2, bold = config.bold },
    Directory = { link = "AthensFg0Bold" },
    Title = { link = "AthensGreenBold" },
    ErrorMsg = { fg = colors.bg0, bg = colors.red, bold = config.bold },
    MoreMsg = { link = "AthensYellowBold" },
    ModeMsg = { link = "AthensYellowBold" },
    Question = { link = "AthensOrangeBold" },
    WarningMsg = { link = "AthensRedBold" },
    LineNr = { fg = colors.fg3 },
    SignColumn = config.transparent_mode and { bg = nil } or { bg = colors.bg1 },
    Folded = { fg = colors.gray, bg = colors.bg1, italic = config.italic.folds },
    FoldColumn = config.transparent_mode and { fg = colors.gray, bg = nil } or { fg = colors.gray, bg = colors.bg1 },
    Cursor = { link = "AthensCursor" },
    vCursor = { link = "Cursor" },
    iCursor = { link = "Cursor" },
    lCursor = { link = "Cursor" },
    Special = { link = "AthensKeyword" },
    Comment = { fg = colors.comment, italic = config.italic.comments },
    Todo = { fg = colors.bg0, bg = colors.yellow, bold = config.bold, italic = config.italic.comments },
    Done = { fg = colors.orange, bold = config.bold, italic = config.italic.comments },
    Error = { fg = colors.err, bold = config.bold, reverse = config.inverse },
    Statement = { link = "AthensText" },
    Conditional = { link = "AthensKeyword" },
    Repeat = { link = "AthensKeyword" },
    Label = { link = "AthensConstant" },
    Exception = { link = "AthensError" },
    Operator = { fg = colors.fg1, italic = config.italic.operators },
    Keyword = { link = "AthensKeyword" },
    Identifier = { link = "AthensVar" },
    Function = { link = "AthensFunction" },
    PreProc = { link = "AthensPreProcessor" },
    Include = { link = "AthensPreProcessor" },
    Define = { link = "AthensPreProcessor" },
    Macro = { link = "AthensPreProcessor" },
    PreCondit = { link = "AthensPreProcessor" },
    Constant = { link = "AthensConstant" },
    Character = { link = "AthensText" },
    String = { fg = colors.str, italic = config.italic.strings },
    Fake = { fg = colors.fake, italic = config.italic.strings },
    Boolean = { link = "AthensText" },
    Number = { link = "AthensText" },
    Float = { link = "AthensText" },
    Type = { link = "AthensType" },
    StorageClass = { link = "AthensKeyword" },
    Structure = { link = "AthensKeyword" },
    Typedef = { link = "AthensKeyword" },
    Pmenu = { fg = colors.fg1, bg = colors.bg2 },
    PmenuSel = { fg = colors.bg2, bg = colors.neutral_orange, bold = config.bold },
    PmenuSbar = { bg = colors.bg2 },
    PmenuThumb = { bg = colors.bg4 },
    DiffDelete = { bg = colors.dark_red },
    DiffAdd = { bg = colors.dark_green },
    DiffChange = { bg = colors.dark_aqua },
    DiffText = { bg = colors.yellow, fg = colors.bg0 },
    SpellCap = { link = "AthensBlueUnderline" },
    SpellBad = { link = "AthensRedUnderline" },
    SpellLocal = { link = "AthensAquaUnderline" },
    SpellRare = { link = "AthensPurpleUnderline" },
    Whitespace = { fg = colors.bg2 },
    Delimiter = { link = "AthensText" },
    EndOfBuffer = { link = "NonText" },
    DiagnosticError = { link = "AthensRed" },
    DiagnosticSignError = { link = "AthensRedSign" },
    DiagnosticUnderlineError = { link = "AthensRedUnderline" },
    DiagnosticWarn = { link = "AthensYellow" },
    DiagnosticSignWarn = { link = "AthensYellowSign" },
    DiagnosticUnderlineWarn = { link = "AthensYellowUnderline" },
    DiagnosticInfo = { link = "AthensBlue" },
    DiagnosticSignInfo = { link = "AthensOrangeNeutralSign" },
    DiagnosticUnderlineInfo = { link = "AthensBlueUnderline" },
    DiagnosticHint = { link = "AthensAqua" },
    DiagnosticSignHint = { link = "AthensAquaSign" },
    DiagnosticUnderlineHint = { link = "AthensAquaUnderline" },
    DiagnosticFloatingError = { link = "AthensRed" },
    DiagnosticFloatingWarn = { link = "AthensOrange" },
    DiagnosticFloatingInfo = { link = "AthensBlue" },
    DiagnosticFloatingHint = { link = "AthensAqua" },
    DiagnosticVirtualTextError = { link = "AthensRed" },
    DiagnosticVirtualTextWarn = { link = "AthensYellow" },
    DiagnosticVirtualTextInfo = { link = "AthensBlue" },
    DiagnosticVirtualTextHint = { link = "AthensAqua" },
    DiagnosticOk = { link = "AthensGreenSign" },
    LspReferenceRead = { link = "AthensYellowBold" },
    LspReferenceText = { link = "AthensYellowBold" },
    LspReferenceWrite = { link = "AthensOrangeBold" },
    LspCodeLens = { link = "AthensGray" },
    LspSignatureActiveParameter = { link = "Search" },
    gitcommitSelectedFile = { fg = colors.neutral_green },
    gitcommitDiscardedFile = { fg = colors.neutral_red },
    GitSignsAdd = { fg = colors.neutral_green },
    GitSignsChange = { fg = colors.neutral_orange },
    GitSignsDelete = { fg = colors.neutral_red },
    NvimTreeSymlink = { fg = colors.neutral_aqua },
    NvimTreeRootFolder = { fg = colors.neutral_purple, bold = true },
    NvimTreeFolderIcon = { fg = colors.neutral_blue, bold = true },
    NvimTreeFileIcon = { fg = colors.fg2 },
    NvimTreeExecFile = { fg = colors.neutral_green, bold = true },
    NvimTreeOpenedFile = { fg = colors.bright_red, bold = true },
    NvimTreeSpecialFile = { fg = colors.neutral_yellow, bold = true, underline = true },
    NvimTreeImageFile = { fg = colors.neutral_purple },
    NvimTreeIndentMarker = { fg = colors.bg3 },
    NvimTreeGitDirty = { fg = colors.neutral_yellow },
    NvimTreeGitStaged = { fg = colors.neutral_yellow },
    NvimTreeGitMerge = { fg = colors.neutral_purple },
    NvimTreeGitRenamed = { fg = colors.neutral_purple },
    NvimTreeGitNew = { fg = colors.neutral_yellow },
    NvimTreeGitDeleted = { fg = colors.neutral_red },
    NvimTreeWindowPicker = { bg = colors.aqua },
    debugPC = { link = "DiffAdd" },
    debugBreakpoint = { link = "AthensRedSign" },
    StartifyBracket = { link = "AthensFg3" },
    StartifyFile = { link = "AthensFg1" },
    StartifyNumber = { link = "AthensBlue" },
    StartifyPath = { link = "AthensGray" },
    StartifySlash = { link = "AthensGray" },
    StartifySection = { link = "AthensYellow" },
    StartifySpecial = { link = "AthensBg2" },
    StartifyHeader = { link = "AthensOrange" },
    StartifyFooter = { link = "AthensBg2" },
    StartifyVar = { link = "StartifyPath" },
    StartifySelect = { link = "Title" },
    DirvishPathTail = { link = "AthensAqua" },
    DirvishArg = { link = "AthensYellow" },
    netrwDir = { link = "AthensAqua" },
    netrwClassify = { link = "AthensAqua" },
    netrwLink = { link = "AthensGray" },
    netrwSymLink = { link = "AthensFg1" },
    netrwExe = { link = "AthensYellow" },
    netrwComment = { link = "AthensGray" },
    netrwList = { link = "AthensBlue" },
    netrwHelpCmd = { link = "AthensAqua" },
    netrwCmdSep = { link = "AthensFg3" },
    netrwVersion = { link = "AthensGreen" },
    NERDTreeDir = { link = "AthensAqua" },
    NERDTreeDirSlash = { link = "AthensAqua" },
    NERDTreeOpenable = { link = "AthensOrange" },
    NERDTreeClosable = { link = "AthensOrange" },
    NERDTreeFile = { link = "AthensFg1" },
    NERDTreeExecFile = { link = "AthensYellow" },
    NERDTreeUp = { link = "AthensGray" },
    NERDTreeCWD = { link = "AthensGreen" },
    NERDTreeHelp = { link = "AthensFg1" },
    NERDTreeToggleOn = { link = "AthensGreen" },
    NERDTreeToggleOff = { link = "AthensRed" },
    CocErrorSign = { link = "AthensRedSign" },
    CocWarningSign = { link = "AthensOrangeSign" },
    CocInfoSign = { link = "AthensBlueSign" },
    CocHintSign = { link = "AthensAquaSign" },
    CocErrorFloat = { link = "AthensRed" },
    CocWarningFloat = { link = "AthensOrange" },
    CocInfoFloat = { link = "AthensBlue" },
    CocHintFloat = { link = "AthensAqua" },
    CocDiagnosticsError = { link = "AthensRed" },
    CocDiagnosticsWarning = { link = "AthensOrange" },
    CocDiagnosticsInfo = { link = "AthensBlue" },
    CocDiagnosticsHint = { link = "AthensAqua" },
    CocSelectedText = { link = "AthensRed" },
    CocMenuSel = { link = "PmenuSel" },
    CocCodeLens = { link = "AthensGray" },
    CocErrorHighlight = { link = "AthensRedUnderline" },
    CocWarningHighlight = { link = "AthensOrangeUnderline" },
    CocInfoHighlight = { link = "AthensBlueUnderline" },
    CocHintHighlight = { link = "AthensAquaUnderline" },
    TelescopeNormal = { link = "AthensFg1" },
    TelescopeSelection = { link = "AthensOrangeBold" },
    TelescopeSelectionCaret = { link = "AthensRed" },
    TelescopeMultiSelection = { link = "AthensGray" },
    TelescopeBorder = { link = "TelescopeNormal" },
    TelescopePromptBorder = { link = "TelescopeNormal" },
    TelescopeResultsBorder = { link = "TelescopeNormal" },
    TelescopePreviewBorder = { link = "TelescopeNormal" },
    TelescopeMatching = { link = "AthensBlue" },
    TelescopePromptPrefix = { link = "AthensRed" },
    TelescopePrompt = { link = "TelescopeNormal" },
    CmpItemAbbr = { link = "AthensFg0" },
    CmpItemAbbrDeprecated = { link = "AthensFg1" },
    CmpItemAbbrMatch = { link = "AthensBlueBold" },
    CmpItemAbbrMatchFuzzy = { link = "AthensBlueUnderline" },
    CmpItemMenu = { link = "AthensGray" },
    CmpItemKindText = { link = "AthensOrange" },
    CmpItemKindVariable = { link = "AthensOrange" },
    CmpItemKindMethod = { link = "AthensBlue" },
    CmpItemKindFunction = { link = "AthensBlue" },
    CmpItemKindConstructor = { link = "AthensYellow" },
    CmpItemKindUnit = { link = "AthensBlue" },
    CmpItemKindField = { link = "AthensBlue" },
    CmpItemKindClass = { link = "AthensYellow" },
    CmpItemKindInterface = { link = "AthensYellow" },
    CmpItemKindModule = { link = "AthensBlue" },
    CmpItemKindProperty = { link = "AthensBlue" },
    CmpItemKindValue = { link = "AthensOrange" },
    CmpItemKindEnum = { link = "AthensYellow" },
    CmpItemKindOperator = { link = "AthensYellow" },
    CmpItemKindKeyword = { link = "AthensPurple" },
    CmpItemKindEvent = { link = "AthensPurple" },
    CmpItemKindReference = { link = "AthensPurple" },
    CmpItemKindColor = { link = "AthensPurple" },
    CmpItemKindSnippet = { link = "AthensGreen" },
    CmpItemKindFile = { link = "AthensBlue" },
    CmpItemKindFolder = { link = "AthensBlue" },
    CmpItemKindEnumMember = { link = "AthensAqua" },
    CmpItemKindConstant = { link = "AthensOrange" },
    CmpItemKindStruct = { link = "AthensYellow" },
    CmpItemKindTypeParameter = { link = "AthensYellow" },
    diffAdded = { link = "DiffAdd" },
    diffRemoved = { link = "DiffDelete" },
    diffChanged = { link = "DiffChange" },
    diffFile = { link = "AthensOrange" },
    diffNewFile = { link = "AthensYellow" },
    diffOldFile = { link = "AthensOrange" },
    diffLine = { link = "AthensBlue" },
    diffIndexLine = { link = "diffChanged" },
    NavicIconsFile = { link = "AthensBlue" },
    NavicIconsModule = { link = "AthensOrange" },
    NavicIconsNamespace = { link = "AthensBlue" },
    NavicIconsPackage = { link = "AthensAqua" },
    NavicIconsClass = { link = "AthensYellow" },
    NavicIconsMethod = { link = "AthensBlue" },
    NavicIconsProperty = { link = "AthensAqua" },
    NavicIconsField = { link = "AthensPurple" },
    NavicIconsConstructor = { link = "AthensBlue" },
    NavicIconsEnum = { link = "AthensPurple" },
    NavicIconsInterface = { link = "AthensGreen" },
    NavicIconsFunction = { link = "AthensBlue" },
    NavicIconsVariable = { link = "AthensPurple" },
    NavicIconsConstant = { link = "AthensOrange" },
    NavicIconsString = { link = "AthensGreen" },
    NavicIconsNumber = { link = "AthensOrange" },
    NavicIconsBoolean = { link = "AthensOrange" },
    NavicIconsArray = { link = "AthensOrange" },
    NavicIconsObject = { link = "AthensOrange" },
    NavicIconsKey = { link = "AthensAqua" },
    NavicIconsNull = { link = "AthensOrange" },
    NavicIconsEnumMember = { link = "AthensYellow" },
    NavicIconsStruct = { link = "AthensPurple" },
    NavicIconsEvent = { link = "AthensYellow" },
    NavicIconsOperator = { link = "AthensRed" },
    NavicIconsTypeParameter = { link = "AthensRed" },
    NavicText = { link = "AthensWhite" },
    NavicSeparator = { link = "AthensWhite" },
    htmlTag = { link = "AthensAquaBold" },
    htmlEndTag = { link = "AthensAquaBold" },
    htmlTagName = { link = "AthensBlue" },
    htmlArg = { link = "AthensOrange" },
    htmlTagN = { link = "AthensFg1" },
    htmlSpecialTagName = { link = "AthensBlue" },
    htmlLink = { fg = colors.fg4, underline = config.underline },
    htmlSpecialChar = { link = "AthensRed" },
    htmlBold = { fg = colors.fg0, bg = colors.bg0, bold = config.bold },
    htmlBoldUnderline = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, underline = config.underline },
    htmlBoldItalic = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, italic = true },
    htmlBoldUnderlineItalic = {
      fg = colors.fg0,
      bg = colors.bg0,
      bold = config.bold,
      italic = true,
      underline = config.underline,
    },
    htmlUnderline = { fg = colors.fg0, bg = colors.bg0, underline = config.underline },
    htmlUnderlineItalic = {
      fg = colors.fg0,
      bg = colors.bg0,
      italic = true,
      underline = config.underline,
    },
    htmlItalic = { fg = colors.fg0, bg = colors.bg0, italic = true },
    xmlTag = { link = "AthensAquaBold" },
    xmlEndTag = { link = "AthensAquaBold" },
    xmlTagName = { link = "AthensBlue" },
    xmlEqual = { link = "AthensBlue" },
    docbkKeyword = { link = "AthensAquaBold" },
    xmlDocTypeDecl = { link = "AthensGray" },
    xmlDocTypeKeyword = { link = "AthensPurple" },
    xmlCdataStart = { link = "AthensGray" },
    xmlCdataCdata = { link = "AthensPurple" },
    dtdFunction = { link = "AthensGray" },
    dtdTagName = { link = "AthensPurple" },
    xmlAttrib = { link = "AthensOrange" },
    xmlProcessingDelim = { link = "AthensGray" },
    dtdParamEntityPunct = { link = "AthensGray" },
    dtdParamEntityDPunct = { link = "AthensGray" },
    xmlAttribPunct = { link = "AthensGray" },
    xmlEntity = { link = "AthensRed" },
    xmlEntityPunct = { link = "AthensRed" },
    clojureKeyword = { link = "AthensBlue" },
    clojureCond = { link = "AthensOrange" },
    clojureSpecial = { link = "AthensOrange" },
    clojureDefine = { link = "AthensOrange" },
    clojureFunc = { link = "AthensYellow" },
    clojureRepeat = { link = "AthensYellow" },
    clojureCharacter = { link = "AthensAqua" },
    clojureStringEscape = { link = "AthensAqua" },
    clojureException = { link = "AthensRed" },
    clojureRegexp = { link = "AthensAqua" },
    clojureRegexpEscape = { link = "AthensAqua" },
    clojureRegexpCharClass = { fg = colors.fg3, bold = config.bold },
    clojureRegexpMod = { link = "clojureRegexpCharClass" },
    clojureRegexpQuantifier = { link = "clojureRegexpCharClass" },
    clojureParen = { link = "AthensFg3" },
    clojureAnonArg = { link = "AthensYellow" },
    clojureVariable = { link = "AthensBlue" },
    clojureMacro = { link = "AthensOrange" },
    clojureMeta = { link = "AthensYellow" },
    clojureDeref = { link = "AthensYellow" },
    clojureQuote = { link = "AthensYellow" },
    clojureUnquote = { link = "AthensYellow" },
    cOperator = { link = "AthensKeyword" },
    cppOperator = { link = "AthensKeyword" },
    cStructure = { link = "AthensKeyword" },
    pythonBuiltin = { link = "AthensOrange" },
    pythonBuiltinObj = { link = "AthensOrange" },
    pythonBuiltinFunc = { link = "AthensOrange" },
    pythonFunction = { link = "AthensFunction" },
    pythonDecorator = { link = "AthensRed" },
    pythonInclude = { link = "AthensBlue" },
    pythonImport = { link = "AthensBlue" },
    pythonRun = { link = "AthensBlue" },
    pythonCoding = { link = "AthensBlue" },
    pythonOperator = { link = "AthensRed" },
    pythonException = { link = "AthensRed" },
    pythonExceptions = { link = "AthensPurple" },
    pythonBoolean = { link = "AthensPurple" },
    pythonDot = { link = "AthensFg3" },
    pythonConditional = { link = "AthensRed" },
    pythonRepeat = { link = "AthensRed" },
    pythonDottedName = { link = "AthensGreenBold" },
    cssBraces = { link = "AthensBlue" },
    cssFunctionName = { link = "AthensFunction" },
    cssIdentifier = { link = "AthensOrange" },
    cssClassName = { link = "AthensGreen" },
    cssColor = { link = "AthensBlue" },
    cssSelectorOp = { link = "AthensBlue" },
    cssSelectorOp2 = { link = "AthensBlue" },
    cssImportant = { link = "AthensGreen" },
    cssVendor = { link = "AthensFg1" },
    cssTextProp = { link = "AthensAqua" },
    cssAnimationProp = { link = "AthensAqua" },
    cssUIProp = { link = "AthensYellow" },
    cssTransformProp = { link = "AthensAqua" },
    cssTransitionProp = { link = "AthensAqua" },
    cssPrintProp = { link = "AthensAqua" },
    cssPositioningProp = { link = "AthensYellow" },
    cssBoxProp = { link = "AthensAqua" },
    cssFontDescriptorProp = { link = "AthensAqua" },
    cssFlexibleBoxProp = { link = "AthensAqua" },
    cssBorderOutlineProp = { link = "AthensAqua" },
    cssBackgroundProp = { link = "AthensAqua" },
    cssMarginProp = { link = "AthensAqua" },
    cssListProp = { link = "AthensAqua" },
    cssTableProp = { link = "AthensAqua" },
    cssFontProp = { link = "AthensAqua" },
    cssPaddingProp = { link = "AthensAqua" },
    cssDimensionProp = { link = "AthensAqua" },
    cssRenderProp = { link = "AthensAqua" },
    cssColorProp = { link = "AthensAqua" },
    cssGeneratedContentProp = { link = "AthensAqua" },
    javaScriptBraces = { link = "AthensFg1" },
    javaScriptFunction = { link = "AthensFunction" },
    javaScriptIdentifier = { link = "AthensRed" },
    javaScriptMember = { link = "AthensBlue" },
    javaScriptNumber = { link = "AthensPurple" },
    javaScriptNull = { link = "AthensPurple" },
    javaScriptParens = { link = "AthensFg3" },
    typescriptReserved = { link = "AthensAqua" },
    typescriptLabel = { link = "AthensAqua" },
    typescriptFuncKeyword = { link = "AthensAqua" },
    typescriptIdentifier = { link = "AthensOrange" },
    typescriptBraces = { link = "AthensFg1" },
    typescriptEndColons = { link = "AthensFg1" },
    typescriptDOMObjects = { link = "AthensFg1" },
    typescriptAjaxMethods = { link = "AthensFg1" },
    typescriptLogicSymbols = { link = "AthensFg1" },
    typescriptDocSeeTag = { link = "Comment" },
    typescriptDocParam = { link = "Comment" },
    typescriptDocTags = { link = "vimCommentTitle" },
    typescriptGlobalObjects = { link = "AthensFg1" },
    typescriptParens = { link = "AthensFg3" },
    typescriptOpSymbols = { link = "AthensFg3" },
    typescriptHtmlElemProperties = { link = "AthensFg1" },
    typescriptNull = { link = "AthensPurple" },
    typescriptInterpolationDelimiter = { link = "AthensAqua" },
    coffeeExtendedOp = { link = "AthensFg3" },
    coffeeSpecialOp = { link = "AthensFg3" },
    coffeeCurly = { link = "AthensOrange" },
    coffeeParen = { link = "AthensFg3" },
    coffeeBracket = { link = "AthensOrange" },
    rubyStringDelimiter = { link = "AthensGreen" },
    rubyInterpolationDelimiter = { link = "AthensAqua" },
    rubyDefinedOperator = { link = "rubyKeyword" },
    objcTypeModifier = { link = "AthensRed" },
    objcDirective = { link = "AthensBlue" },
    goDirective = { link = "AthensAqua" },
    goConstants = { link = "AthensPurple" },
    goDeclaration = { link = "AthensRed" },
    goDeclType = { link = "AthensBlue" },
    goBuiltins = { link = "AthensOrange" },
    luaIn = { link = "AthensRed" },
    luaFunction = { link = "AthensFunction" },
    luaTable = { link = "AthensOrange" },
    moonSpecialOp = { link = "AthensFg3" },
    moonExtendedOp = { link = "AthensFg3" },
    moonFunction = { link = "AthensFunction" },
    moonObject = { link = "AthensYellow" },
    javaAnnotation = { link = "AthensBlue" },
    javaDocTags = { link = "AthensAqua" },
    javaCommentTitle = { link = "vimCommentTitle" },
    javaParen = { link = "AthensFg3" },
    javaParen1 = { link = "AthensFg3" },
    javaParen2 = { link = "AthensFg3" },
    javaParen3 = { link = "AthensFg3" },
    javaParen4 = { link = "AthensFg3" },
    javaParen5 = { link = "AthensFg3" },
    javaOperator = { link = "AthensOrange" },
    javaVarArg = { link = "AthensGreen" },
    elixirDocString = { link = "Comment" },
    elixirStringDelimiter = { link = "AthensGreen" },
    elixirInterpolationDelimiter = { link = "AthensAqua" },
    elixirModuleDeclaration = { link = "AthensYellow" },
    makeSpecial = { link = "AthensText" },
    markdownItalic = { fg = colors.fg3, italic = true },
    markdownBold = { fg = colors.fg3, bold = config.bold },
    markdownBoldItalic = { fg = colors.fg3, bold = config.bold, italic = true },
    markdownH1 = { link = "AthensGreenBold" },
    markdownH2 = { link = "AthensGreenBold" },
    markdownH3 = { link = "AthensYellowBold" },
    markdownH4 = { link = "AthensYellowBold" },
    markdownH5 = { link = "AthensYellow" },
    markdownH6 = { link = "AthensYellow" },
    markdownCode = { link = "AthensAqua" },
    markdownCodeBlock = { link = "AthensAqua" },
    markdownCodeDelimiter = { link = "AthensAqua" },
    markdownBlockquote = { link = "AthensGray" },
    markdownListMarker = { link = "AthensGray" },
    markdownOrderedListMarker = { link = "AthensGray" },
    markdownRule = { link = "AthensGray" },
    markdownHeadingRule = { link = "AthensGray" },
    markdownUrlDelimiter = { link = "AthensFg3" },
    markdownLinkDelimiter = { link = "AthensFg3" },
    markdownLinkTextDelimiter = { link = "AthensFg3" },
    markdownHeadingDelimiter = { link = "AthensOrange" },
    markdownUrl = { link = "AthensPurple" },
    markdownUrlTitleDelimiter = { link = "AthensGreen" },
    markdownLinkText = { fg = colors.gray, underline = config.underline },
    markdownIdDeclaration = { link = "markdownLinkText" },
    haskellType = { link = "AthensBlue" },
    haskellIdentifier = { link = "AthensAqua" },
    haskellSeparator = { link = "AthensFg4" },
    haskellDelimiter = { link = "AthensOrange" },
    haskellOperators = { link = "AthensPurple" },
    haskellBacktick = { link = "AthensOrange" },
    haskellStatement = { link = "AthensPurple" },
    haskellConditional = { link = "AthensPurple" },
    haskellLet = { link = "AthensRed" },
    haskellDefault = { link = "AthensRed" },
    haskellWhere = { link = "AthensRed" },
    haskellBottom = { link = "AthensRedBold" },
    haskellImportKeywords = { link = "AthensPurpleBold" },
    haskellDeclKeyword = { link = "AthensOrange" },
    haskellDecl = { link = "AthensOrange" },
    haskellDeriving = { link = "AthensPurple" },
    haskellAssocType = { link = "AthensAqua" },
    haskellNumber = { link = "AthensAqua" },
    haskellPragma = { link = "AthensRedBold" },
    haskellTH = { link = "AthensAquaBold" },
    haskellForeignKeywords = { link = "AthensGreen" },
    haskellKeyword = { link = "AthensRed" },
    haskellFloat = { link = "AthensAqua" },
    haskellInfix = { link = "AthensPurple" },
    haskellQuote = { link = "AthensGreenBold" },
    haskellShebang = { link = "AthensYellowBold" },
    haskellLiquid = { link = "AthensPurpleBold" },
    haskellQuasiQuoted = { link = "AthensBlueBold" },
    haskellRecursiveDo = { link = "AthensPurple" },
    haskellQuotedType = { link = "AthensRed" },
    haskellPreProc = { link = "AthensFg4" },
    haskellTypeRoles = { link = "AthensRedBold" },
    haskellTypeForall = { link = "AthensRed" },
    haskellPatternKeyword = { link = "AthensBlue" },
    jsonKeyword = { link = "AthensGreen" },
    jsonQuote = { link = "AthensGreen" },
    jsonBraces = { link = "AthensFg1" },
    jsonString = { link = "AthensFg1" },
    mailQuoted1 = { link = "AthensAqua" },
    mailQuoted2 = { link = "AthensPurple" },
    mailQuoted3 = { link = "AthensYellow" },
    mailQuoted4 = { link = "AthensGreen" },
    mailQuoted5 = { link = "AthensRed" },
    mailQuoted6 = { link = "AthensOrange" },
    mailSignature = { link = "Comment" },
    csBraces = { link = "AthensFg1" },
    csEndColon = { link = "AthensFg1" },
    csLogicSymbols = { link = "AthensFg1" },
    csParens = { link = "AthensFg3" },
    csOpSymbols = { link = "AthensFg3" },
    csInterpolationDelimiter = { link = "AthensFg3" },
    csInterpolationAlignDel = { link = "AthensAquaBold" },
    csInterpolationFormat = { link = "AthensAqua" },
    csInterpolationFormatDel = { link = "AthensAquaBold" },
    rustSigil = { link = "AthensText" },
    rustEscape = { link = "AthensAqua" },
    rustStringContinuation = { link = "AthensAqua" },
    rustEnum = { link = "AthensAqua" },
    rustStructure = { link = "AthensAqua" },
    rustModPathSep = { link = "AthensFg2" },
    rustCommentLineDoc = { link = "Comment" },
    rustDefault = { link = "AthensAqua" },
    ocamlOperator = { link = "AthensFg1" },
    ocamlKeyChar = { link = "AthensOrange" },
    ocamlArrow = { link = "AthensOrange" },
    ocamlInfixOpKeyword = { link = "AthensRed" },
    ocamlConstructor = { link = "AthensOrange" },
    LspSagaCodeActionTitle = { link = "Title" },
    LspSagaCodeActionBorder = { link = "AthensFg1" },
    LspSagaCodeActionContent = { fg = colors.green, bold = config.bold },
    LspSagaLspFinderBorder = { link = "AthensFg1" },
    LspSagaAutoPreview = { link = "AthensOrange" },
    TargetWord = { fg = colors.blue, bold = config.bold },
    FinderSeparator = { link = "AthensAqua" },
    LspSagaDefPreviewBorder = { link = "AthensBlue" },
    LspSagaHoverBorder = { link = "AthensOrange" },
    LspSagaRenameBorder = { link = "AthensBlue" },
    LspSagaDiagnosticSource = { link = "AthensOrange" },
    LspSagaDiagnosticBorder = { link = "AthensPurple" },
    LspSagaDiagnosticHeader = { link = "AthensGreen" },
    LspSagaSignatureHelpBorder = { link = "AthensGreen" },
    SagaShadow = { link = "AthensBg0" },
    DashboardShortCut = { link = "AthensOrange" },
    DashboardHeader = { link = "AthensAqua" },
    DashboardCenter = { link = "AthensYellow" },
    DashboardFooter = { fg = colors.purple, italic = true },
    MasonHighlight = { link = "AthensAqua" },
    MasonHighlightBlock = { fg = colors.bg0, bg = colors.blue },
    MasonHighlightBlockBold = { fg = colors.bg0, bg = colors.blue, bold = true },
    MasonHighlightSecondary = { fg = colors.yellow },
    MasonHighlightBlockSecondary = { fg = colors.bg0, bg = colors.yellow },
    MasonHighlightBlockBoldSecondary = { fg = colors.bg0, bg = colors.yellow, bold = true },
    MasonHeader = { link = "MasonHighlightBlockBoldSecondary" },
    MasonHeaderSecondary = { link = "MasonHighlightBlockBold" },
    MasonMuted = { fg = colors.fg4 },
    MasonMutedBlock = { fg = colors.bg0, bg = colors.fg4 },
    MasonMutedBlockBold = { fg = colors.bg0, bg = colors.fg4, bold = true },
    LspInlayHint = { link = "comment" },
    CarbonFile = { link = "AthensFg1" },
    CarbonExe = { link = "AthensYellow" },
    CarbonSymlink = { link = "AthensAqua" },
    CarbonBrokenSymlink = { link = "AthensRed" },
    CarbonIndicator = { link = "AthensGray" },
    CarbonDanger = { link = "AthensRed" },
    CarbonPending = { link = "AthensYellow" },
    NoiceCursor = { link = "TermCursor" },
    NotifyDEBUGBorder = { link = "AthensBlue" },
    NotifyDEBUGIcon = { link = "AthensBlue" },
    NotifyDEBUGTitle = { link = "AthensBlue" },
    NotifyERRORBorder = { link = "AthensRed" },
    NotifyERRORIcon = { link = "AthensRed" },
    NotifyERRORTitle = { link = "AthensRed" },
    NotifyINFOBorder = { link = "AthensAqua" },
    NotifyINFOIcon = { link = "AthensAqua" },
    NotifyINFOTitle = { link = "AthensAqua" },
    NotifyTRACEBorder = { link = "AthensGreen" },
    NotifyTRACEIcon = { link = "AthensGreen" },
    NotifyTRACETitle = { link = "AthensGreen" },
    NotifyWARNBorder = { link = "AthensYellow" },
    NotifyWARNIcon = { link = "AthensYellow" },
    NotifyWARNTitle = { link = "AthensYellow" },
    IlluminatedWordText = { link = "LspReferenceText" },
    IlluminatedWordRead = { link = "LspReferenceRead" },
    IlluminatedWordWrite = { link = "LspReferenceWrite" },
    TSRainbowRed = { fg = colors.red },
    TSRainbowOrange = { fg = colors.orange },
    TSRainbowYellow = { fg = colors.yellow },
    TSRainbowGreen = { fg = colors.green },
    TSRainbowBlue = { fg = colors.blue },
    TSRainbowViolet = { fg = colors.purple },
    TSRainbowCyan = { fg = colors.aqua },
    RainbowDelimiterRed = { fg = colors.red },
    RainbowDelimiterOrange = { fg = colors.orange },
    RainbowDelimiterYellow = { fg = colors.yellow },
    RainbowDelimiterGreen = { fg = colors.green },
    RainbowDelimiterBlue = { fg = colors.blue },
    RainbowDelimiterViolet = { fg = colors.purple },
    RainbowDelimiterCyan = { fg = colors.aqua },
    DapBreakpointSymbol = { fg = colors.red, bg = colors.bg1 },
    DapStoppedSymbol = { fg = colors.green, bg = colors.bg1 },
    DapUIBreakpointsCurrentLine = { link = "AthensYellow" },
    DapUIBreakpointsDisabledLine = { link = "AthensGray" },
    DapUIBreakpointsInfo = { link = "AthensAqua" },
    DapUIBreakpointsLine = { link = "AthensYellow" },
    DapUIBreakpointsPath = { link = "AthensBlue" },
    DapUICurrentFrameName = { link = "AthensPurple" },
    DapUIDecoration = { link = "AthensPurple" },
    DapUIEndofBuffer = { link = "EndOfBuffer" },
    DapUIFloatBorder = { link = "AthensAqua" },
    DapUILineNumber = { link = "AthensYellow" },
    DapUIModifiedValue = { link = "AthensRed" },
    DapUIPlayPause = { fg = colors.green, bg = colors.bg1 },
    DapUIRestart = { fg = colors.green, bg = colors.bg1 },
    DapUIScope = { link = "AthensBlue" },
    DapUISource = { link = "AthensFg1" },
    DapUIStepBack = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepInto = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepOut = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepOver = { fg = colors.blue, bg = colors.bg1 },
    DapUIStop = { fg = colors.red, bg = colors.bg1 },
    DapUIStoppedThread = { link = "AthensBlue" },
    DapUIThread = { link = "AthensBlue" },
    DapUIType = { link = "AthensOrange" },
    DapUIUnavailable = { link = "AthensGray" },
    DapUIWatchesEmpty = { link = "AthensGray" },
    DapUIWatchesError = { link = "AthensRed" },
    DapUIWatchesValue = { link = "AthensYellow" },
    DapUIWinSelect = { link = "AthensYellow" },
    NeogitDiffDelete = { link = "DiffDelete" },
    NeogitDiffAdd = { link = "DiffAdd" },
    NeogitHunkHeader = { link = "WinBar" },
    NeogitHunkHeaderHighlight = { link = "WinBarNC" },
    DiffviewStatusModified = { link = "AthensGreenBold" },
    DiffviewFilePanelInsertions = { link = "AthensGreenBold" },
    DiffviewFilePanelDeletions = { link = "AthensRedBold" },
    MiniAnimateCursor = { reverse = true, nocombine = true },
    MiniAnimateNormalFloat = { fg = colors.fg1, bg = colors.bg1 },
    MiniClueBorder = { link = "FloatBorder" },
    MiniClueDescGroup = { link = "DiagnosticFloatingWarn" },
    MiniClueDescSingle = { link = "NormalFloat" },
    MiniClueNextKey = { link = "DiagnosticFloatingHint" },
    MiniClueNextKeyWithPostkeys = { link = "DiagnosticFloatingError" },
    MiniClueSeparator = { link = "DiagnosticFloatingInfo" },
    MiniClueTitle = { link = "FloatTitle" },
    MiniCompletionActiveParameter = { underline = true },
    MiniCursorword = { underline = true },
    MiniCursorwordCurrent = { underline = true },
    MiniDepsChangeAdded = { link = "AthensGreen" },
    MiniDepsChangeRemoved = { link = "AthensRed" },
    MiniDepsHint = { link = "DiagnosticHint" },
    MiniDepsInfo = { link = "DiagnosticInfo" },
    MiniDepsMsgBreaking = { link = "DiagnosticWarn" },
    MiniDepsPlaceholder = { link = "Comment" },
    MiniDepsTitle = { link = "Title" },
    MiniDepsTitleError = { link = "DiffDelete" },
    MiniDepsTitleSame = { link = "DiffChange" },
    MiniDepsTitleUpdate = { link = "DiffAdd" },
    MiniDiffOverAdd = { link = "DiffAdd" },
    MiniDiffOverChange = { link = "DiffText" },
    MiniDiffOverContext = { link = "DiffChange" },
    MiniDiffOverDelete = { link = "DiffDelete" },
    MiniDiffSignAdd = { link = "AthensGreen" },
    MiniDiffSignChange = { link = "AthensAqua" },
    MiniDiffSignDelete = { link = "AthensRed" },
    MiniFilesBorder = { link = "FloatBorder" },
    MiniFilesBorderModified = { link = "DiagnosticFloatingWarn" },
    MiniFilesCursorLine = { bg = colors.bg2 },
    MiniFilesDirectory = { link = "Directory" },
    MiniFilesFile = { link = "AthensFg1" },
    MiniFilesNormal = { link = "NormalFloat" },
    MiniFilesTitle = { link = "FloatTitle" },
    MiniFilesTitleFocused = { link = "AthensOrangeBold" },
    MiniHipatternsFixme = { fg = colors.bg0, bg = colors.red, bold = config.bold },
    MiniHipatternsHack = { fg = colors.bg0, bg = colors.yellow, bold = config.bold },
    MiniHipatternsNote = { fg = colors.bg0, bg = colors.blue, bold = config.bold },
    MiniHipatternsTodo = { fg = colors.bg0, bg = colors.aqua, bold = config.bold },
    MiniIconsAzure = { link = "AthensBlue" },
    MiniIconsBlue = { link = "AthensBlue" },
    MiniIconsCyan = { link = "AthensAqua" },
    MiniIconsGreen = { link = "AthensGreen" },
    MiniIconsGrey = { link = "AthensFg0" },
    MiniIconsOrange = { link = "AthensOrange" },
    MiniIconsPurple = { link = "AthensPurple" },
    MiniIconsRed = { link = "AthensRed" },
    MiniIconsYellow = { link = "AthensYellow" },
    MiniIndentscopeSymbol = { link = "AthensGray" },
    MiniIndentscopeSymbolOff = { link = "AthensYellow" },
    MiniJump = { link = "AthensOrangeUnderline" },
    MiniJump2dDim = { link = "AthensGray" },
    MiniJump2dSpot = { fg = colors.orange, bold = config.bold, nocombine = true },
    MiniJump2dSpotAhead = { fg = colors.aqua, bg = colors.bg0, nocombine = true },
    MiniJump2dSpotUnique = { fg = colors.yellow, bold = config.bold, nocombine = true },
    MiniMapNormal = { link = "NormalFloat" },
    MiniMapSymbolCount = { link = "Special" },
    MiniMapSymbolLine = { link = "Title" },
    MiniMapSymbolView = { link = "Delimiter" },
    MiniNotifyBorder = { link = "FloatBorder" },
    MiniNotifyNormal = { link = "NormalFloat" },
    MiniNotifyTitle = { link = "FloatTitle" },
    MiniOperatorsExchangeFrom = { link = "IncSearch" },
    MiniPickBorder = { link = "FloatBorder" },
    MiniPickBorderBusy = { link = "DiagnosticFloatingWarn" },
    MiniPickBorderText = { link = "FloatTitle" },
    MiniPickIconDirectory = { link = "Directory" },
    MiniPickIconFile = { link = "MiniPickNormal" },
    MiniPickHeader = { link = "DiagnosticFloatingHint" },
    MiniPickMatchCurrent = { bg = colors.bg2 },
    MiniPickMatchMarked = { link = "Visual" },
    MiniPickMatchRanges = { link = "DiagnosticFloatingHint" },
    MiniPickNormal = { link = "NormalFloat" },
    MiniPickPreviewLine = { link = "CursorLine" },
    MiniPickPreviewRegion = { link = "IncSearch" },
    MiniPickPrompt = { link = "DiagnosticFloatingInfo" },
    MiniStarterCurrent = { nocombine = true },
    MiniStarterFooter = { link = "AthensGray" },
    MiniStarterHeader = { link = "Title" },
    MiniStarterInactive = { link = "Comment" },
    MiniStarterItem = { link = "Normal" },
    MiniStarterItemBullet = { link = "Delimiter" },
    MiniStarterItemPrefix = { link = "WarningMsg" },
    MiniStarterSection = { link = "Delimiter" },
    MiniStarterQuery = { link = "MoreMsg" },
    MiniStatuslineDevinfo = { link = "StatusLine" },
    MiniStatuslineFileinfo = { link = "StatusLine" },
    MiniStatuslineFilename = { link = "StatusLineNC" },
    MiniStatuslineInactive = { link = "StatusLineNC" },
    MiniStatuslineModeCommand = { fg = colors.bg0, bg = colors.yellow, bold = config.bold },
    MiniStatuslineModeInsert = { fg = colors.bg0, bg = colors.blue, bold = config.bold },
    MiniStatuslineModeNormal = { fg = colors.bg0, bg = colors.fg1, bold = config.bold },
    MiniStatuslineModeOther = { fg = colors.bg0, bg = colors.aqua, bold = config.bold },
    MiniStatuslineModeReplace = { fg = colors.bg0, bg = colors.red, bold = config.bold },
    MiniStatuslineModeVisual = { fg = colors.bg0, bg = colors.green, bold = config.bold },
    MiniSurround = { link = "IncSearch" },
    MiniTablineCurrent = { fg = colors.green, bg = colors.bg1, bold = config.bold, reverse = config.invert_tabline },
    MiniTablineFill = { link = "TabLineFill" },
    MiniTablineHidden = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
    MiniTablineModifiedCurrent = {
      fg = colors.bg1,
      bg = colors.green,
      bold = config.bold,
      reverse = config.invert_tabline,
    },
    MiniTablineModifiedHidden = { fg = colors.bg1, bg = colors.bg4, reverse = config.invert_tabline },
    MiniTablineModifiedVisible = { fg = colors.bg1, bg = colors.fg1, reverse = config.invert_tabline },
    MiniTablineTabpagesection = { link = "Search" },
    MiniTablineVisible = { fg = colors.fg1, bg = colors.bg1, reverse = config.invert_tabline },
    MiniTestEmphasis = { bold = config.bold },
    MiniTestFail = { link = "AthensRedBold" },
    MiniTestPass = { link = "AthensGreenBold" },
    MiniTrailspace = { bg = colors.red },
    ["@comment"] = { link = "Comment" },
    ["@none"] = { bg = "NONE", fg = "NONE" },
    ["@preproc"] = { link = "PreProc" },
    ["@define"] = { link = "Define" },
    ["@operator"] = { link = "Operator" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { link = "Delimiter" },
    ["@punctuation.special"] = { link = "Delimiter" },
    ["@string"] = { link = "String" },
    ["@string.regex"] = { link = "String" },
    ["@string.regexp"] = { link = "String" },
    ["@string.escape"] = { link = "String" },
    ["@string.special"] = { link = "SpecialChar" },
    ["@string.special.path"] = { link = "Underlined" },
    ["@string.special.symbol"] = { link = "Identifier" },
    ["@string.special.url"] = { link = "Underlined" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@boolean"] = { link = "Boolean" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@float"] = { link = "Float" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { link = "Special" },
    ["@function.call"] = { link = "AthensText" },
    ["@function.macro"] = { link = "Macro" },
    ["@function.method"] = { link = "AthensText" },
    ["@method"] = { link = "Function" },
    ["@method.call"] = { link = "AthensText" },
    ["@constructor"] = { link = "AthensText" },
    ["@parameter"] = { link = "Identifier" },
    ["@keyword"] = { link = "AthensKeyword" },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.debug"] = { link = "Debug" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.function"] = { link = "AthensKeyword" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.operator"] = { link = "AthensKeyword" },
    ["@keyword.repeat"] = { link = "AthensKeyword" },
    ["@keyword.return"] = { link = "AthensKeyword" },
    ["@keyword.storage"] = { link = "StorageClass" },
    ["@conditional"] = { link = "Conditional" },
    ["@repeat"] = { link = "Repeat" },
    ["@debug"] = { link = "Debug" },
    ["@label"] = { link = "Label" },
    ["@include"] = { link = "Include" },
    ["@exception"] = { link = "Exception" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { link = "Type" },
    ["@type.definition"] = { link = "Typedef" },
    ["@type.qualifier"] = { link = "Type" },
    ["@storageclass"] = { link = "StorageClass" },
    ["@attribute"] = { link = "PreProc" },
    ["@field"] = { link = "Identifier" },
    ["@property"] = { link = "AthensText" },
    ["@variable"] = { link = "AthensFg1" },
    ["@variable.builtin"] = { link = "Special" },
    ["@variable.member"] = { link = "Identifier" },
    ["@variable.parameter"] = { link = "Identifier" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "AthensConstant" },
    ["@constant.macro"] = { link = "Define" },
    ["@markup"] = { link = "AthensFg1" },
    ["@markup.strong"] = { bold = config.bold },
    ["@markup.italic"] = { link = "@text.emphasis" },
    ["@markup.underline"] = { underline = config.underline },
    ["@markup.strikethrough"] = { strikethrough = config.strikethrough },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.raw"] = { link = "String" },
    ["@markup.math"] = { link = "Special" },
    ["@markup.environment"] = { link = "Macro" },
    ["@markup.environment.name"] = { link = "Type" },
    ["@markup.link"] = { link = "Underlined" },
    ["@markup.link.label"] = { link = "SpecialChar" },
    ["@markup.list"] = { link = "Delimiter" },
    ["@markup.list.checked"] = { link = "AthensGreen" },
    ["@markup.list.unchecked"] = { link = "AthensGray" },
    ["@comment.todo"] = { link = "Todo" },
    ["@comment.note"] = { link = "SpecialComment" },
    ["@comment.warning"] = { link = "WarningMsg" },
    ["@comment.error"] = { link = "ErrorMsg" },
    ["@diff.plus"] = { link = "diffAdded" },
    ["@diff.minus"] = { link = "diffRemoved" },
    ["@diff.delta"] = { link = "diffChanged" },
    ["@module"] = { link = "AthensFg1" },
    ["@namespace"] = { link = "AthensFg1" },
    ["@symbol"] = { link = "Identifier" },
    ["@text"] = { link = "AthensFg1" },
    ["@text.strong"] = { bold = config.bold },
    ["@text.emphasis"] = { italic = config.italic.emphasis },
    ["@text.underline"] = { underline = config.underline },
    ["@text.strike"] = { strikethrough = config.strikethrough },
    ["@text.title"] = { link = "Title" },
    ["@text.literal"] = { link = "String" },
    ["@text.uri"] = { link = "Underlined" },
    ["@text.math"] = { link = "Special" },
    ["@text.environment"] = { link = "Macro" },
    ["@text.environment.name"] = { link = "Type" },
    ["@text.reference"] = { link = "Constant" },
    ["@text.todo"] = { link = "Todo" },
    ["@text.todo.checked"] = { link = "AthensGreen" },
    ["@text.todo.unchecked"] = { link = "AthensGray" },
    ["@text.note"] = { link = "SpecialComment" },
    ["@text.note.comment"] = { fg = colors.purple, bold = config.bold },
    ["@text.warning"] = { link = "WarningMsg" },
    ["@text.danger"] = { link = "ErrorMsg" },
    ["@text.danger.comment"] = { fg = colors.fg0, bg = colors.red, bold = config.bold },
    ["@text.diff.add"] = { link = "diffAdded" },
    ["@text.diff.delete"] = { link = "diffRemoved" },
    ["@tag"] = { link = "Tag" },
    ["@tag.attribute"] = { link = "Identifier" },
    ["@tag.delimiter"] = { link = "Delimiter" },
    ["@punctuation"] = { link = "Delimiter" },
    ["@macro"] = { link = "Macro" },
    ["@Structure"] = { link = "Structure" },
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.decorator"] = { link = "@macro" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.interface"] = { link = "@constructor" },
    ["@lsp.type.macro"] = { link = "@macro" },
    ["@lsp.type.method"] = { link = "@method" },
    ["@lsp.type.namespace"] = { link = "@namespace" },
    ["@lsp.type.parameter"] = { link = "@parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"] = { link = "@variable" },
  }

  for group, hl in pairs(config.overrides) do
    if groups[group] then
      -- "link" should not mix with other configs (:h hi-link)
      groups[group].link = nil
    end

    groups[group] = vim.tbl_extend("force", groups[group] or {}, hl)
  end

  return groups
end

---@param config AthensConfig?
Athens.setup = function(config)
  Athens.config = vim.tbl_deep_extend("force", Athens.config, config or {})
end

--- main load function
Athens.load = function()
  if vim.version().minor < 8 then
    vim.notify_once("athens.nvim: you must use neovim 0.8 or higher")
    return
  end

  -- reset colors
  if vim.g.colors_name then
    vim.cmd.hi("clear")
  end
  vim.g.colors_name = "athens"
  vim.o.termguicolors = true

  local groups = get_groups()

  -- add highlights
  for group, settings in pairs(groups) do
    vim.api.nvim_set_hl(0, group, settings)
  end
end

return Athens
